-- Seed data for Cosmic WebApp Backend
-- The activity and reccuring lookup tables have been removed (migration 005).
-- task_type and recurrence_rule are now free-text fields on the tasks table.
-- Supply these values directly when creating tasks via the API.
